### ISSUE TITLE
Missing ifaa manager

### ISSUE THREAD

**Issue by krmax44** [sm6150-dev/android_device_xiaomi_sm6150-common#4]
The build with this repo fails, as ifaa manager is demanded in the Makefile, but not present in the repo:

https://github.com/sm6150-dev/android_device_xiaomi_sm6150-common/blob/f2d113e6bf23fad920078f1f95c57332c937cea6/sm6150.mk#L235-L239

Yielded error:

```
internal error: failed to find dex jar path for module "org.ifaa.android.manager"
internal error: failed to find dex jar path for module "org.ifaa.android.manager"
```

It is however present in upstream: 

https://github.com/LineageOS/android_device_xiaomi_sm6150-common/blob/3accca0aa0922b68b04641b9a911b297474fbbb7/org.ifaa.android.manager/src/org/ifaa/android/manager/IFAAManager.java#L1

Personally I just removed the lines in the Makefile as it seems unnecessary in my region anyhow. But might be something worth taking a look at.

**Comment by merothh** [comment]
https://github.com/sm6150-dev/android_hardware_xiaomi
